version: '3.3'

networks:
  newrelic-php:
    driver: bridge

services:
  bmi-calculation-api:
    image: registry.gitlab.com/mamazary/bmi-calculation-api
    ports:
      - '8889:80'
    env_file:
      - docker-compose.env
    environment:
      - SENTRY_DSN=$CI_SENTRY_DSN
      - NEW_RELIC_AGENT_VERSION=$NEW_RELIC_AGENT_VERSION
      - NEW_RELIC_LICENSE_KEY=$NEW_RELIC_LICENSE_KEY
      - NEW_RELIC_APPNAME=$NEW_RELIC_APPNAME
    restart: always
    networks:
      - newrelic-php

  papertrail-logging:
    image: gliderlabs/logspout
    environment:
      - SYSLOG_HOSTNAME={{.ContainerName}}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - syslog+tls://$PT_LOGN.papertrailapp.com:$PT_PORT
    restart: always

  newrelic-php-daemon:
    image: newrelic/php-daemon
    restart: always
    networks:
      - newrelic-php
